// Generated by CoffeeScript 2.5.1
(function() {
  var atlas;

  atlas = require("./atlasCreator")("blocks", 16, `${__dirname}/blocks`, `${__dirname}/../client/static/assets/blocks`, 694, 36, true, 27);

}).call(this);
