// Generated by CoffeeScript 2.5.1
(function() {
  var atlas;

  atlas = require("./atlasCreator")("items", 50, `${__dirname}/items`, `${__dirname}/../client/static/assets/items`, 975, 32, false, 0);

}).call(this);
