// Generated by CoffeeScript 2.5.1
var Chat;

Chat = class Chat {
  constructor(game) {
    this.game = game;
    this.chatDiv = document.querySelector(".chat");
    this.listen();
    this.history = [];
    return;
  }

  listen() {
    var _this;
    _this = this;
    window.addEventListener("wheel", function(e) {
      if (_this.game.FPC.gameState !== "chat") {
        e.preventDefault();
      }
    }, {
      passive: false
    });
    return this;
  }

  isElementScrolledToBottom(el) {
    if (el.scrollTop >= (el.scrollHeight - el.offsetHeight)) {
      return true;
    }
    return false;
  }

  scrollToBottom(el) {
    el.scrollTop = el.scrollHeight;
  }

  log(message) {
    var atBottom;
    atBottom = this.isElementScrolledToBottom(this.chatDiv);
    $(".chat").append(message + "<br>");
    if (atBottom) {
      this.scrollToBottom(this.chatDiv);
    }
  }

  command(com) {
    if (com !== "") {
      this.history.push(com);
      return this.game.socket.emit("command", com);
    }
  }

};

export {
  Chat
};
