// Generated by CoffeeScript 2.5.1
var Entities;

import * as THREE from './build/three.module.js';

Entities = class Entities {
  constructor(options) {
    this.scene = options.scene;
    this.saved = {};
  }

  update(entities) {
    var cube, geometry, i, material, results;
    for (i in entities) {
      if (entities[i].type !== "player") {
        if (this.saved[entities[i].uuid] === void 0) {
          console.log(entities[i]);
          geometry = new THREE.BoxGeometry(1, 1, 1);
          material = new THREE.MeshBasicMaterial({
            color: 0x00ff00
          });
          cube = new THREE.Mesh(geometry, material);
          this.scene.add(cube);
          cube.position.set(entities[i].position.x + 0.5, entities[i].position.y + 16, entities[i].position.z + 0.5);
          this.saved[entities[i].uuid] = cube;
          this.saved[entities[i].uuid].active = true;
        } else {
          this.saved[entities[i].uuid].position.set(entities[i].position.x + 0.5, entities[i].position.y + 16, entities[i].position.z + 0.5);
          this.saved[entities[i].uuid].active = true;
        }
      }
    }
    for (i in this.saved) {
      if (this.saved[i].active === false) {
        this.scene.remove(this.saved[i]);
        delete this.saved[i];
      }
    }
    results = [];
    for (i in this.saved) {
      results.push(this.saved[i].active = false);
    }
    return results;
  }

};

export {
  Entities
};
