// Generated by CoffeeScript 2.5.1
var InventoryBar,
  modulo = function(a, b) { return (+a % (b = +b) + b) % b; };

InventoryBar = class InventoryBar {
  constructor(options) {
    var i, j, k, l;
    for (i = j = 0; j <= 9; i = ++j) {
      $(".player_hp").append("<span class='hp'></span> ");
    }
    for (i = k = 0; k <= 9; i = ++k) {
      $(".player_food").append("<span class='food'></span> ");
    }
    for (i = l = 1; l <= 9; i = ++l) {
      $(".inv_bar").append("<span class='inv_box'></span> ");
    }
  }

  setHp(points) {
    var i, j, k, l, lista, ref;
    lista = {};
    for (i = j = 1; j <= 10; i = ++j) {
      lista[i - 1] = "empty";
      $(".hp").eq(i - 1).removeClass("empty");
      $(".hp").eq(i - 1).removeClass("full");
      $(".hp").eq(i - 1).removeClass("half");
    }
    if (points !== 0) {
      for (i = k = 1, ref = (points + points % 2) / 2; (1 <= ref ? k <= ref : k >= ref); i = 1 <= ref ? ++k : --k) {
        lista[i - 1] = "full";
      }
      if (points % 2 === 1) {
        lista[(points + points % 2) / 2 - 1] = "half";
      }
    }
    for (i = l = 1; l <= 10; i = ++l) {
      $(".hp").eq(i - 1).addClass(lista[i - 1]);
    }
  }

  setFood(points) {
    var i, j, k, l, lista, ref;
    lista = {};
    for (i = j = 1; j <= 10; i = ++j) {
      lista[10 - i] = "empty";
      $(".food").eq(10 - i).removeClass("empty");
      $(".food").eq(10 - i).removeClass("full");
      $(".food").eq(10 - i).removeClass("half");
    }
    if (points !== 0) {
      for (i = k = 1, ref = (points + points % 2) / 2; (1 <= ref ? k <= ref : k >= ref); i = 1 <= ref ? ++k : --k) {
        lista[10 - i] = "full";
      }
      if (points % 2 === 1) {
        lista[10 - (points + points % 2) / 2] = "half";
      }
    }
    for (i = l = 1; l <= 10; i = ++l) {
      $(".food").eq(10 - i).addClass(lista[10 - i]);
    }
  }

  setXp(level, progress) {
    $(".player_xp").text(level);
    return $(".xp_bar").css("width", `${500 * progress}px`);
  }

  setFocus(num) {
    return $(".inv_cursor").css("left", `calc(50vw - 253px + 55*${num}px)`);
  }

  updateInv(inv) {
    var i, j;
    for (i = j = 36; j <= 44; i = ++j) {
      if (inv[i] !== null) {
        $(".inv_box").eq(i - 36).css("background-image", `url(/assets/items/${inv[i].name}.png)`);
      } else {
        $(".inv_box").eq(i - 36).css("background-image", "");
      }
    }
  }

  listen() {
    var _this, focus;
    focus = 0;
    this.setFocus(focus);
    _this = this;
    return $(window).on('wheel', function(e) {
      if (e.originalEvent.deltaY > 0) {
        focus++;
      } else {
        focus--;
      }
      focus = modulo(focus, 9);
      return _this.setFocus(focus);
    });
  }

};

export {
  InventoryBar
};
