// Generated by CoffeeScript 2.5.1
(function() {
  var State, handlers;

  addEventListener("message", function(e) {
    var fn;
    fn = handlers[e.data.type];
    if (!fn) {
      throw new Error('no handler for type: ' + e.data.type);
    }
    fn(e.data.data);
  });

  State = {
    init: null,
    world: {}
  };

  handlers = {
    init: function(data) {
      console.log("WORKER: Successfully loaded assets!");
      State.init = data;
    },
    setVoxel: function(data) {
      State.world[`${data.voxelX}:${data.voxelY}:${data.voxelZ}`] = data.value;
      return console.log("WORKER: Voxel saved!", State.world);
    },
    genCellGeo: function(data) {
      var normals, positions, uvs;
      console.log("Ready to generate cell geometry");
      positions = [];
      normals = [];
      uvs = [];
    }
  };

}).call(this);
