// Generated by CoffeeScript 2.5.1
(function() {
  addEventListener("message", function(e) {
    var mess;
    mess = e.data;
    if (mess.type === "assets") {
      console.log(mess.data);
    }
  });

}).call(this);
