// Generated by CoffeeScript 2.5.1
(function() {
  //Terrain Worker

  //load necessary models data (example: anvil-normals,uvs,positions)
  addEventListener("message", function(e) {
    console.log(e.data);
  });

  //listen chunk sending (cellSize+2)^3 and response array of uvs,normals,positions

}).call(this);
