// Generated by CoffeeScript 2.5.1
(function() {
  var eula_txt, exec, fs, process, server_jar, start_sh, util, wget;

  util = require("util");

  exec = require('child_process').exec;

  fs = require("fs");

  process = require('child_process');

  wget = function(url, result) {
    var child;
    return child = exec('curl ' + url + ' > ' + result, function(error, stdout, stderr) {
      if (error !== null) {
        return console.log('exec error: ' + error);
      }
    });
  };

  server_jar = __dirname + "/../minecraft/server.jar";

  eula_txt = __dirname + "/../minecraft/eula.txt";

  start_sh = __dirname + "/../minecraft/start.sh";

  if (!fs.existsSync(server_jar)) {
    console.log("Downloading server jar...");
    wget('https://cdn.getbukkit.org/spigot/spigot-1.16.1.jar', server_jar);
  } else {
    console.log("Server.jar already exist");
  }

  console.log("Writing eula.txt file...");

  fs.writeFileSync(eula_txt, "#Sat Oct 10 16:00:22 CEST 2020\neula=true");

  console.log("Writing start.sh file...");

  fs.writeFileSync(start_sh, `#!/bin/bash\njava -jar ${server_jar} nogui`);

  console.log("RUNNING SERVER!");

  process.spawn(`${start_sh}`, [], {
    stdio: 'inherit'
  });

}).call(this);
