// Generated by CoffeeScript 2.5.1
(function() {
  var config, fs, opn;

  opn = require("opn");

  fs = require("fs");

  config = JSON.parse(fs.readFileSync(__dirname + "/../config.json"));

  require("./server")(config);

  opn(`http://${config.host}:${config['express-port']}`);

}).call(this);
