// Generated by CoffeeScript 2.5.1
(function() {
  var config, el, fs;

  el = require("electron");

  fs = require("fs");

  config = JSON.parse(fs.readFileSync(__dirname + "/config.json"));

  require("./server")(config);

  el.app.on('ready', function() {
    var size, win;
    size = el.screen.getPrimaryDisplay().size;
    win = new el.BrowserWindow({
      width: size.width,
      height: size.height,
      icon: __dirname + "/client/assets/images/icon.png"
    });
    win.setMenuBarVisibility(false);
    win.setAutoHideMenuBar(true);
    return win.loadURL(`http://${config.host}:${config['express-port']}`);
  });

}).call(this);
