// Generated by CoffeeScript 2.5.1
(function() {
  var JSSoup, fs, http, https, options, request;

  request = require('request');

  JSSoup = require('jssoup').default;

  fs = require('fs');

  http = require("http");

  https = require("https");

  options = {
    method: 'GET',
    url: "https://www.digminecraft.com/lists/item_id_list_pc.php",
    encoding: "utf-8"
  };

  request(options, function(err, response, body) {
    var i, j, k, l, last, len, map, ref, ref1, soup, title, type, war;
    soup = new JSSoup(body);
    map = {};
    last = null;
    ref = soup.findAll("td");
    for (k = 0, len = ref.length; k < len; k++) {
      i = ref[k];
      if ((i.text !== "&nbsp;") && (i.text.includes("minecraft:"))) {
        title = i.text.split("(")[0];
        war = 0;
        for (j = l = 0, ref1 = i.text.length - 1; (0 <= ref1 ? l <= ref1 : l >= ref1); j = 0 <= ref1 ? ++l : --l) {
          if (i.text[j] === "(") {
            war = j;
          }
        }
        type = (i.text.substr(war + 11)).split(")")[0];
        console.log(type, last);
        (function(type, url) {
          var file;
          file = fs.createWriteStream(`${__dirname}/client/assets/items/${type}.png`);
          return https.get(url, function(response) {
            return response.pipe(file);
          });
        })(type, `https://www.digminecraft.com${last}`);
      } else if (i.find("img") !== void 0) {
        last = i.find("img").attrs["data-src"];
      }
    }
  });

}).call(this);
