// Generated by CoffeeScript 2.5.1
(function() {
  var common, merge;

  merge = require("webpack-merge");

  common = require("./webpack.common.js");

  module.exports = merge.merge(common, {
    devtool: 'source-map',
    mode: "production"
  });

}).call(this);
