// Generated by CoffeeScript 2.5.1
(function() {
  var common, merge;

  merge = require("webpack-merge");

  common = require("./webpack.common.js");

  module.exports = merge.merge(common, {
    mode: "development",
    devServer: {
      contentBase: `${__dirname}/public`,
      port: 8080
    }
  });

}).call(this);
